#Module      : LABEL
#Description : Terraform label module variables.
variable "name" {
  type        = string
  default     = ""
  description = "Name  (e.g. `app` or `cluster`)."
}


variable "environment" {
  type        = string
  default     = ""
  description = "Environment (e.g. `prod`, `dev`, `staging`)."
}


variable "enabled" {
  type        = bool
  default     = false
  description = "Flag to control the module creation."
}

variable "managedby" {
  type        = string
  default     = "hello@clouddrove.com"
  description = "ManagedBy, eg 'CloudDrove'"
}

variable "label_order" {
  type        = list(any)
  default     = []
  description = "Label order, e.g. `name`,`application`."
}

variable "kms_key_id" {
  type        = string
  default     = ""
  description = "The ARN for the KMS encryption key. When specifying kms_key_id, encrypted needs to be set to true."
}

variable "instance_tags" {
  type        = map(any)
  default     = {}
  description = "Instance tags."
}

## Inspector

variable "duration" {
  type        = number
  default     = 3600
  description = "The duration of the inspector run."
}

## Lambda

variable "lambda_enabled" {
  type        = bool
  default     = true
  description = "Whether to create the resources. Set to `false` to prevent the module from creating any resources."
}

variable "schedule_expression" {
  type        = string
  default     = "cron(0 14 ? * THU *)" # Run every Thursday at 2PM UTC/9AM EST/10AM EDT
  description = "AWS Schedule Expression: https://docs.aws.amazon.com/AmazonCloudWatch/latest/events/ScheduledEvents.html"
}

variable "rule_iam_role_arn" {
  default     = null
  description = "The Amazon Resource Name (ARN) associated with the role that is used for target invocation."
}

variable "is_enabled" {
  type        = bool
  default     = true
  description = "Whether the rule should be enabled (defaults to true)."
}

variable "target_iam_role_arn" {
  default     = null
  description = "The Amazon Resource Name (ARN) associated with the role that is used for target invocation."
}

variable "iam_actions" {
  type        = list(any)
  default     = []
  description = "The actions for Iam Role Policy."
}

variable "handler" {
  type        = string
  default     = ""
  description = "The function entrypoint in your code."
}

variable "runtime" {
  type        = string
  default     = ""
  description = "Runtimes."
}

variable "timeout" {
  type        = number
  default     = 120
  description = "The amount of time your Lambda Function has to run in seconds. Defaults to 3."
}

variable "statement_ids" {
  type        = list(string)
  default     = []
  description = "A unique statement identifier. By default generated by Terraform. "
}

variable "actions" {
  type        = list(string)
  default     = []
  description = "The AWS Lambda action you want to allow in this statement. (e.g. lambda:InvokeFunction)."
}

variable "principals" {
  type        = list(string)
  default     = []
  description = "The principal who is getting this permission. e.g. s3.amazonaws.com, an AWS account ID, or any valid AWS service principal such as events.amazonaws.com or sns.amazonaws.com."
}
